### ISSUE TITLE
Integration into EasyLM

### ISSUE THREAD

**Issue by versae** [davisyoshida/lorax#2] opened 2023-07-11 12:04 UTC
Hi! Cool project. I wonder how hard it would be to implement an integration of this library into something like @young-geng's [EasyLM](https://github.com/young-geng/EasyLM). That would make using `lorax` really easy as all the training would be handled by EasyLM.

**Comment by davisyoshida** [comment] 2023-07-11 20:03
I've never used EasyLM but the intention is that Lorax should be able to transform arbitrary JAX functions, so it should just work out of the box. If you try it and it doesn't work, let me know what the issue is and I'll try to help.

**Comment by young-geng** [comment] 2023-07-11 23:36
As the creator of EasyLM, I imagine that EasyLM might not be the best fit for doing LoRA style training. EasyLM is mainly focused on scaling up the training, where the majority of the heavy lifting is built to support partitioning the model across many accelerators distributed in many hosts. Most of these utils will probably be not very useful in the low resource settings when LoRA is needed.

**Comment by davisyoshida** [comment] 2023-07-11 23:55
@young-geng Sounds reasonable. I think there may be some use cases down the line with batched LoRAs on a shared trunk, but unless that picks up popularity it won't be worth it for you to add it.

Since this doesn't seem to be a Lorax issue per se, I'm going to go ahead and close it.

**Closed as completed by davisyoshida** 2023-07-11 23:55 UTC

**Comment by versae** [comment] 2023-07-12 06:14
Thanks for the discussion! I still see the utility of having LoRA for training large models on single TPU VMs. I'll play around :)
